import Header from "@/components/Header/Header";
import Head from "next/head";

export default function About (){
    return(
        <>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Header/>

            <div className="main">
                <div className="image-container">
                    <img className="image" src="../../shop.jpg" alt="Descriptive Alt Text"/>
                    <div className="text-overlay">About Us</div>
                </div>
                <div className="text-container">
                    Welcome to [Your Shop Name], where fashion meets quality and style is accessible to all. Nestled in
                    the
                    heart of [City, State], our boutique has been the go-to destination for fashion enthusiasts seeking
                    unique, trend-setting pieces since [Year of Establishment]. Our mission is simple: to provide a
                    curated
                    selection of high-quality apparel that empowers individuals to express their personal style with
                    confidence.
                    <br/>
                    At [Your Shop Name], we believe in the power of fashion to transform and inspire. Our collection
                    ranges
                    from timeless classics to contemporary trends, featuring a diverse array of clothing options for
                    men,
                    women, and children. Each piece in our store is carefully selected to ensure it meets our high
                    standards
                    for quality, sustainability, and ethical production.
                    <br/>
                    Our passionate team is dedicated to delivering an exceptional shopping experience, offering
                    personalized
                    styling advice and attentive customer service. Whether you're searching for the perfect outfit for a
                    special occasion or everyday wear, we're here to help you find pieces that you'll love and wear with
                    pride.
                    <br/>
                    Join us at [Your Shop Name] and discover the joy of dressing well. Follow us on social media for the
                    latest arrivals, style tips, and exclusive events. Welcome to our community of fashion lovers - we
                    can't
                    wait to style you!
                </div>
            </div>

            <style jsx>{`
                .text-container {
                    font-family: "Josefin Sans", sans-serif;
                    max-width: 80%;
                    padding: 12px;
                    font-weight: 400;
                    font-size: 14px;
                    line-height: 22px;
                    text-align: justify;
                    text-justify: inter-word;
                    color: rgba(0, 0, 0, 0.6);
                }
                
                .image-container {
                    position: relative;
                    text-align: center;
                    color: white;
                    width: 80%;
                }

                .image-container::after {
                    content: "";
                    position: absolute;
                    top: 0;
                    left: 0;
                    right: 0;
                    bottom: 5px;
                    border-radius: 20px;
                }

                /* Style the image (optional) */
                .image-container img {
                    width: 90%; /* or any specific dimensions */
                    border-radius: 20px;
                }

                .text-overlay {
                    position: absolute;
                    top: 50%;
                    left: 50%;
                    transform: translate(-50%, -50%);
                    /* Additional styling for the text */
                    font-size: 3rem; /* Example size */
                    color: white; /* Text color */
                    z-index: 999;
                    opacity: 0.7;
                }


                .main {
                    font-family: "Josefin Sans", sans-serif;
                    display: flex;
                    flex-direction: column;
                    align-items: center;
                }

                .card-title {
                    margin-top: 10px;
                    font-size: 14px;
                    font-weight: 700;
                    color: #000000;
                }

                .price {
                    margin-top: 5px;
                    font-weight: 700;
                    color: #000000;
                    font-size: 16px;
                }
                
                

            `}</style>
        </>
    );
}