import Head from "next/head";
import Header from "@/components/Header/Header";
import Cover from "@/components/Cover/Cover";
import NewArrivals from "@/components/NewArraivels/newArrivals";

export default function Home() {
  return (
      <div className="main">
          <Head>
              <title>Store with NextJS</title>
              <meta name="description" content="Generated by create next app"/>
              <meta name="viewport" content="width=device-width, initial-scale=1"/>
              <link rel="icon" href="/favicon.ico"/>
          </Head>
          <Header/>
          <Cover/>
          <NewArrivals/>
          <style global jsx>{`
              body{
                  display: flex;
                  flex-direction: column;
                  margin: 0 !important;
                  width:100%;
              }
          `}</style>
      </div>
  );
}
